*** %LET ALL_LEADS_HIST_LOC =                                       ***;
*** "\\mktg-app01\E\Vishwa\webreport\Production\Web\AllApps_History_2.xlsx"***;

PROC IMPORT 
	DATAFILE = &ALL_LEADS_HIST_LOC. DBMS = EXCEL OUT = LEAD_IMPORT_FILE
	REPLACE;
RUN;

*** CHECKS ------------------------------------------------------- ***;
PROC SQL;
	SELECT MIN(ENTDATE) AS MIN_ENTDATE,
		   MAX(ENTDATE) AS MAX_ENTDATE,
		   MIN(LEADDATE) AS MIN_LEADDATE FORMAT date9.,
		   MAX(LEADDATE) AS MAX_LEADDATE FORMAT date9.,
		   MIN(NETLOANAMOUNT) AS MIN_NETLOANAMOUNT,
		   MAX(NETLOANAMOUNT) AS MAX_NETLOANAMOUNT
		  /* MIN(NETLOANAMT_201802) AS MIN_NETLOANAMOUNT_201802, */
		  /* MAX(NETLOANAMT_201802) AS MAX_NETLOANAMOUNT_201802 */
	FROM LEAD_IMPORT_FILE 
 /* WHERE NETLOANAMOUNT > 0 */;
QUIT;

DATA LEAD_IMPORT_FILE;
	SET LEAD_IMPORT_FILE;
	costperloan2 = input(costperloan, 12.);
	DROP costperloan;
RUN;

DATA LEAD_IMPORT_FILE_2;
	SET LEAD_IMPORT_FILE;
	LENGTH LEADNUMBER $10 PORTALLEADID $10 LTFILTER_ROUTINGID $10
		   WORKPHONE $12 CELLPHONE $12 FIRSTNAME $50 MIDDLENAME $50
		   LASTNAME $50 EMAIL $100 FULLADDRESS $120 ADR1 $80 ADR2 $25
		   CITY $50 LOANTYPE $25 AFFILIATE $25;
	IF LOANTYPE = "Lending Tree PQ" THEN AFFILIATE = "Lending Tree";
	ELSE AFFILIATE = "Web";
	IF SOURCE = "CreditKarma" THEN AFFILIATE = "Credit Karma";
	IF SOURCE = "SuperMoney LLC" THEN AFFILIATE = "Super Money";
	costperloan = input(costperloan2, 12.);
	CLASSID2 = CLASSID * 1;
	APRATE2 = APRATE * 1;
	EFFRATE2 = EFFRATE * 1;
	ORGTERM2 = ORGTERM * 1;
	CRSCORE2 = CRSCORE * 1;
	NETLOANAMOUNT2 = NETLOANAMOUNT * 1;
	ENTYRMONTH2 = ENTYRMONTH * 1;
	ENTDATE_SAS2 = INPUT(STRIP(TRIM(ENTDATE)), yymmdd10.);
	LEADDATEMINUSENTDATE2 = (LEADDATE - INPUT(STRIP(TRIM(ENTDATE)),
											yymmdd10.)) * 1;
	ENTDATEMINUSLEADDATE2 = (INPUT(STRIP(TRIM(ENTDATE)), 
								  yymmdd10.) - LEADDATE) * 1;
	LEADFICO2 = SUBSTR(STRIP(TRIM(LEADFICO)), 1, 3) * 1;
	BOOKED_MONTH2 = MONTH(INPUT(ENTDATE, yymmdd10.));
	TOTALLOANCOST2 = INPUT(TOTALLOANCOST, 5.);
	TOTALLEADCOST = COSTPERLEAD * TOTALLEADS;
	DROP TOTALLOANCOST BOOKED_MONTH LEADFICO CLASSID APRATE EFFRATE
		 ORGTERM CRSCORE NETLOANAMOUNT ENTDATE_SAS LEADDATEMINUSENTDATE
		 ENTDATEMINUSLEADDATE ENTYRMONTH costperloan2 LEADMONTH BOOKED;
	RENAME TOTALLOANCOST2 = TOTALLOANCOST 
		   BOOKED_MONTH2 = BOOKED_MONTH 
		   LEADFICO2 = LEADFICO 
		   CLASSID2 = CLASSID 
		   APRATE2 = APRATE 
		   EFFRATE2 = EFFRATE 
		   ORGTERM2 = ORGTERM 
		   CRSCORE2 = CRSCORE 
		   NETLOANAMOUNT2 = NETLOANAMOUNT 
		   ENTDATE_SAS2 = ENTDATE_SAS 
		   LEADDATEMINUSENTDATE2 = LEADDATEMINUSENTDATE
		   ENTDATEMINUSLEADDATE2 = ENTDATEMINUSLEADDATE
		   ENTYRMONTH2 = ENTYRMONTH;
RUN;

DATA LEAD_IMPORT_FILE_2;
	LENGTH LEADNUMBER $10 PORTALLEADID $10 LTFILTER_ROUTINGID $10
		   WORKPHONE $12 CELLPHONE $12 FIRSTNAME $50 MIDDLENAME $50
		   LASTNAME $50 EMAIL $100 FULLADDRESS $120 ADR1 $80 ADR2 $25
		   CITY $50 LOANTYPE $25 AFFILIATE $25;
	SET LEAD_IMPORT_FILE_2 &NEW_MONTH_FILE;
RUN;

***CHECKS -------------------------------------------------------- ***;
PROC SQL;
	SELECT ENTYRMONTH, SUM(BOOKED) 
	FROM LEAD_IMPORT_FILE_2 
	GROUP BY 1;

	SELECT LEADYRMONTH, COUNT(LEADNUMBER) 
	FROM LEAD_IMPORT_FILE_2 
	GROUP BY 1;
QUIT;

DATA LEAD_IMPORT_FILE_2;
	SET LEAD_IMPORT_FILE_2;
	FORMAT ENTDATE_SAS date9.;
RUN;

DATA MERGED_XX;
	*SET &LEAD_IMPORT_FILE;
	SET LEAD_IMPORT_FILE_2;
	IF LEADYRMONTH NE &RECENT_MONTH_NO;
RUN;

DATA &TWO_MO_BOOKED &TWO_MO_UNBOOKED;
	SET MERGED_XX; /* LAST ITERATION OF FINAL FILE */
	IF LEADYRMONTH = &TWO_MO_AGO;
	IF BOOKED = 1 THEN OUTPUT &TWO_MO_BOOKED;
	ELSE OUTPUT &TWO_MO_UNBOOKED;
RUN;

PROC SORT 
	DATA = VW_L; 
	BY SSNO1; 
RUN;

PROC SORT 
	DATA = &TWO_MO_UNBOOKED; 
	BY SSNO1; 
RUN;

DATA MADES_A;
	MERGE &TWO_MO_UNBOOKED(IN = x) VW_L(IN = y);
	BY SSNO1;
	IF x = 1;
RUN;

DATA MADES_A;
	SET MADES_A;
	IF ENTDATE_SAS >= LEADDATE_SAS - 1 AND 
					  ENTDATE_SAS <= LEADDATE_SAS + 60 
		THEN BOOKED = 1;
	ELSE BOOKED = 0;
	IF BOOKED = 0 THEN BRACCTNO = "";
	IF OWNBR = "" THEN OWNBR = DWOWNBR;
RUN;

DATA MADES_A;
	SET MADES_A &TWO_MO_BOOKED;
RUN;

PROC SORT 
	DATA = MADES_A; 
	BY BRACCTNO AFFILIATE; 
RUN;

DATA UNBOOKED BOOKED;
	SET MADES_A;
	IF BRACCTNO = "" THEN OUTPUT UNBOOKED;
	ELSE OUTPUT BOOKED;
RUN;

DATA x y;
	SET BOOKED;
	BY BRACCTNO;
	IF FIRST.BRACCTNO & LAST.BRACCTNO THEN OUTPUT x;
	ELSE OUTPUT y;
RUN;

PROC SORT 
	DATA = y OUT = y NODUPKEY;
	BY BRACCTNO AFFILIATE;
RUN;

PROC SORT 
	DATA = y OUT = y;
	BY BRACCTNO LEADDATE;
RUN;

DATA y2;
	SET y;
	BY BRACCTNO LEADDATE;
	PRIORITY = FIRST.BRACCTNO;
RUN;

DATA y3;
	SET y2;
	IF priority = 0 THEN BRACCTNO = "";
	IF priority = 0 THEN BOOKED = 0;
RUN;

DATA MADES_D;
	SET UNBOOKED x y3;
RUN;

DATA FINAL;
	SET MADES_D;

	IF BOOKED = 0 THEN DO;
		NETLOANAMOUNT = .;
		ENTDATE_SAS = .;
		TOTALLOANCOST = .;
		BRACCTNO = "";
		ENTYRMONTH = .;
	END;

	IF BOOKED = 1 THEN DO;
		TOTALLOANCOST = 80;
		BOOKED_MONTH = MONTH(ENTDATE_SAS);
	END;

	LEADMONTH = MONTH(LEADDATE_SAS);
	TOTALLEADS = 1;
	IF AMTREQUESTED < 5000 THEN COSTPERLEAD = 2;
	ELSE COSTPERLEAD = 3;
	COSTPERLOAN = 80;
RUN;

***CHECKS -------------------------------------------------------- ***;
PROC SQL;
	SELECT ENTYRMONTH, SUM(BOOKED) 
	FROM FINAL 
	GROUP BY 1;
QUIT;

DATA &LEADS_MINUS_2_MO_AGO;
	SET MERGED_XX;
	IF LEADYRMONTH NE &TWO_MO_AGO;
RUN;

DATA &ALL_LEADS_FILE;
	SET &LEADS_MINUS_2_MO_AGO FINAL;
RUN;

*** HERE WE ARE IDENTIFYING LOANS BOOKED THIS MONTH FROM LAST      ***;
*** MONTH'S LEADS ----------------------------------------- ***;
DATA &ONE_MO_BOOKED &ONE_MO_UNBOOKED;
	SET &ALL_LEADS_FILE;
	IF LEADYRMONTH = &ONE_MO_AGO;
	IF BOOKED = 1 THEN OUTPUT &ONE_MO_BOOKED;
	ELSE OUTPUT &ONE_MO_UNBOOKED;
RUN;

PROC SORT 
	DATA = VW_L; 
	BY SSNO1; 
RUN;

PROC SORT 
	DATA = &ONE_MO_UNBOOKED; 
	BY SSNO1;
RUN;

DATA MADES_A;
	MERGE &ONE_MO_UNBOOKED(IN = x) VW_L(IN = y);
	BY SSNO1;
	IF x = 1;
RUN;

DATA MADES_A;
	SET MADES_A;
	IF ENTDATE_SAS >= LEADDATE_SAS - 1 AND 
	   ENTDATE_SAS <= LEADDATE_SAS + 60 THEN BOOKED = 1;
	ELSE BOOKED = 0;
	IF BOOKED = 0 THEN BRACCTNO = "";
	IF OWNBR = "" THEN OWNBR = DWOWNBR;
RUN;

DATA MADES_A;
	SET MADES_A &ONE_MO_BOOKED;
RUN;

PROC SORT
	DATA = MADES_A;
	BY BRACCTNO AFFILIATE;
RUN;

DATA UNBOOKED BOOKED;
	SET MADES_A;
	IF BRACCTNO = "" THEN OUTPUT UNBOOKED;
	ELSE OUTPUT BOOKED;
RUN;

DATA x y;
	SET BOOKED;
	BY BRACCTNO;
	IF FIRST.BRACCTNO & LAST.BRACCTNO THEN OUTPUT x;
	ELSE OUTPUT y;
RUN;

PROC SORT 
	DATA = y OUT = y NODUPKEY;
	BY BRACCTNO AFFILIATE LEADYRMONTH;
RUN;

PROC SORT 
	DATA = y OUT = y;
	BY BRACCTNO LEADDATE;
RUN;

DATA y2;
	SET y;
	BY BRACCTNO LEADDATE;
	PRIORITY = FIRST.BRACCTNO;
RUN;

DATA y3;
	SET y2;
	IF priority = 0 THEN BRACCTNO = "";
	IF priority = 0 THEN BOOKED = 0;
RUN;

DATA MADES_D;
	SET UNBOOKED x y3;
RUN;

DATA FINAL;
	SET MADES_D;

	IF BOOKED = 0 THEN DO;
		NETLOANAMOUNT = .;
		ENTDATE_SAS = .;
		TOTALLOANCOST = .;
		BRACCTNO = "";
	END;

	IF BOOKED = 1 THEN DO;
		TOTALLOANCOST = 80;
		BOOKED_MONTH = MONTH(ENTDATE_SAS);
	END;

	LEADMONTH = MONTH(LEADDATE_SAS);
	TOTALLEADS = 1;
	IF AMTREQUESTED < 5000 THEN COSTPERLEAD = 2;
	ELSE COSTPERLEAD = 3;
	COSTPERLOAN = 80;
RUN;

DATA &LEADS_MINUS_1_MO_AGO;
	SET &ALL_LEADS_FILE;
	IF LEADYRMONTH NE &ONE_MO_AGO;
RUN;

DATA &ALL_LEADS_FILE_2;
	SET &LEADS_MINUS_1_MO_AGO FINAL;
RUN;
