%LET LEADMONTH = 03;
%LET LEADYRMONTH = 202003;
%LET BOOK_MONTH = 03;

TITLE;

PROC FORMAT;
	PICTURE PCTPIC(ROUND) LOW - HIGH = '09.00%';
RUN; 

PROC SORT 
	DATA = ALL_LEADS_3;
	BY SOURCE;
RUN;

ODS EXCEL OPTIONS(SHEET_INTERVAL = "None");
TITLE "Month Summary";

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS LEADYRMONTH LEADSTATE;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADSTATE ALL, 
		   TOTALLEADS * F = comma18.0
		   PREAPPROVED_FLAG = "# Auto Apprv" * F = comma18.0 
		   PREAPPROVED_FLAG = "% approve" * ROWPCTSUM < TOTALLEADS > * F
			= PCTPIC. / NOCELLMERGE;
	WHERE LEADYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS BOOKED_MONTH LEADSTATE;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADSTATE ALL, 
		   BOOKED = "Booked" * F = comma18.0 
		   NETLOANAMOUNT = "$ Booked" * F = dollar18.0 
		   NETLOANAMOUNT * MEAN = "avg adv" * F = dollar18.0
			/ NOCELLMERGE;
	WHERE BOOKED_MONTH = &BOOK_MONTH & ENTYRMONTH = &LEADYRMONTH;
RUN;

TITLE "Web Leads";

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS LEADYRMONTH LEADSTATE;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADSTATE ALL, 
		   TOTALLEADS * F = comma18.0 
		   PREAPPROVED_FLAG = "# Auto Apprv" * F = comma18.0 
		   PREAPPROVED_FLAG = "% approve" * ROWPCTSUM < TOTALLEADS > * F
			= PCTPIC. / NOCELLMERGE;
	BY SOURCE LEADMONTH;
	WHERE SOURCE = 'Web Leads' & LEADYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS BOOKED_MONTH LEADSTATE;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADSTATE ALL, 
		   BOOKED = "BOOKED" * F = comma18.0 
		   NETLOANAMOUNT = "$ BOOKED" * F = dollar18.0 
		   NETLOANAMOUNT * MEAN = "avg adv" * F = dollar18.0
			/ NOCELLMERGE;
	WHERE SOURCE = 'Web Leads' & BOOKED_MONTH = &BOOK_MONTH & ENTYRMONTH = &LEADYRMONTH;
RUN;

TITLE "Lending Tree";

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS LEADYRMONTH LEADSTATE;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADSTATE ALL, 
		   TOTALLEADS * F = comma18.0 
		   PREAPPROVED_FLAG = "# Auto Apprv" * F = comma18.0 
		   PREAPPROVED_FLAG = "% approve" * ROWPCTSUM < TOTALLEADS > * F
			= PCTPIC. / NOCELLMERGE;
	BY SOURCE;
	WHERE SOURCE = 'LendingTree' & LEADYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS BOOKED_MONTH LEADSTATE;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADSTATE ALL, 
		   BOOKED = "BOOKED" * F = comma18.0 
		   NETLOANAMOUNT = "$ BOOKED" * F = dollar18.0 
		   NETLOANAMOUNT * MEAN = "avg adv" * F = dollar18.0
			/ NOCELLMERGE;
	WHERE SOURCE = 'LendingTree' & BOOKED_MONTH = &BOOK_MONTH & ENTYRMONTH = &LEADYRMONTH;
RUN;

TITLE "Credit Karma";

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS LEADYRMONTH LEADSTATE;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADSTATE ALL, 
		   TOTALLEADS * F = comma18.0 
		   PREAPPROVED_FLAG = "# Auto Apprv" * F = comma18.0 
		   PREAPPROVED_FLAG = "% approve" * ROWPCTSUM < TOTALLEADS > * F
			= PCTPIC. / NOCELLMERGE;
	BY SOURCE;
	WHERE SOURCE = 'CreditKarma' & LEADYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS BOOKED_MONTH LEADSTATE;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADSTATE ALL, 
		   BOOKED = "BOOKED" * F = comma18.0 
		   NETLOANAMOUNT = "$ BOOKED" * F = dollar18.0 
		   NETLOANAMOUNT * MEAN = "avg adv" * F = dollar18.0
			/ NOCELLMERGE;
	WHERE SOURCE = 'CreditKarma' & BOOKED_MONTH = &BOOK_MONTH & ENTYRMONTH = &LEADYRMONTH;
RUN;

TITLE "SuperMoney LLC";

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS LEADYRMONTH LEADSTATE;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADSTATE ALL, 
		   TOTALLEADS * F = comma18.0 
		   PREAPPROVED_FLAG = "# Auto Apprv" * F = comma18.0 
		   PREAPPROVED_FLAG = "% approve" * ROWPCTSUM < TOTALLEADS > * F
			= PCTPIC. / NOCELLMERGE;
	BY SOURCE;
	WHERE SOURCE = 'SuperMoney LLC' & LEADYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS BOOKED_MONTH LEADSTATE;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADSTATE ALL, 
		   BOOKED = "BOOKED" * F = comma18.0 
		   NETLOANAMOUNT = "$ BOOKED" * F = dollar18.0 
		   NETLOANAMOUNT * MEAN = "avg adv" * F = dollar18.0
			/ NOCELLMERGE;
	WHERE SOURCE = 'SuperMoney LLC' & BOOKED_MONTH = &BOOK_MONTH & ENTYRMONTH = &LEADYRMONTH;
RUN;

ODS EXCEL CLOSE;

*** BY VP AND SUPERVISOR ----------------------------------------- ***;
%LET LEADMONTH = 03;
%LET LEADYRMONTH = 202003;
%LET BOOK_MONTH = 03;

PROC SORT 
	DATA = ALL_LEADS_3;
	BY VP;
RUN;

ODS EXCEL OPTIONS(SHEET_INTERVAL="NONE");

TITLE "Web Leads";

PROC TABULATE 
	DATA = ALL_LEADS_3 MISSING;
	CLASS SUPERVISOR VP LEADYRMONTH LEADSTATE;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADYRMONTH, 
		TOTALLEADS * F = comma18.0 
		PREAPPROVED_FLAG = "# Auto Apprv" * F = comma18.0 
		PREAPPROVED_FLAG = "% approve" * ROWPCTSUM < TOTALLEADS > * F = PCTPIC./NOCELLMERGE;
	WHERE SOURCE = 'Web Leads' & LEADYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3 MISSING;
	CLASS SUPERVISOR VP LEADYRMONTH LEADSTATE;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADYRMONTH * SUPERVISOR ALL, 
		TOTALLEADS * F = comma18.0 
		PREAPPROVED_FLAG = "# Auto Apprv" * F = comma18.0 
		PREAPPROVED_FLAG = "% approve" * ROWPCTSUM < TOTALLEADS > * F = PCTPIC./NOCELLMERGE;
	BY VP;
	WHERE SOURCE = 'Web Leads' & LEADYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA=ALL_LEADS_3 MISSING;
	CLASS SUPERVISOR VP BOOKED_MONTH LEADSTATE;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES BOOKED_MONTH * SUPERVISOR ALL, 
		BOOKED = "BOOKED" * F = comma18.0 
		NETLOANAMOUNT = "$ BOOKED" * F = dollar18.0 
		NETLOANAMOUNT * MEAN = "avg adv" * F = dollar18.0/NOCELLMERGE;
	BY VP;
	WHERE SOURCE = 'Web Leads' & BOOKED_MONTH = &BOOK_MONTH & ENTYRMONTH = &LEADYRMONTH;
RUN;

ODS EXCEL CLOSE;
ODS EXCEL OPTIONS(SHEET_INTERVAL="NONE");

TITLE "Lending Tree";

PROC TABULATE 
	DATA = ALL_LEADS_3 MISSING;
	CLASS SUPERVISOR VP LEADYRMONTH LEADSTATE;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADYRMONTH, 
		TOTALLEADS * F = comma18.0 
		PREAPPROVED_FLAG = "# Auto Apprv" * F = comma18.0 
		PREAPPROVED_FLAG = "% approve" * ROWPCTSUM < TOTALLEADS > * F = PCTPIC./NOCELLMERGE;
	WHERE SOURCE = 'LendingTree' & LEADYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3 MISSING;
	CLASS SUPERVISOR VP LEADYRMONTH LEADSTATE;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADYRMONTH * SUPERVISOR ALL, 
		TOTALLEADS * F = comma18.0 
		PREAPPROVED_FLAG = "# Auto Apprv" * F = comma18.0 
		PREAPPROVED_FLAG = "% approve" * ROWPCTSUM < TOTALLEADS > * F = PCTPIC./NOCELLMERGE;
	BY VP;
	WHERE SOURCE = 'LendingTree' & LEADYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3 MISSING;
	CLASS SUPERVISOR VP BOOKED_MONTH LEADSTATE;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES BOOKED_MONTH * SUPERVISOR ALL, 
		BOOKED = "BOOKED" * F = comma18.0 
		NETLOANAMOUNT = "$ BOOKED" * F = dollar18.0 
		NETLOANAMOUNT * MEAN = "avg adv" * F = dollar18.0/NOCELLMERGE;
	BY VP;
	WHERE SOURCE = 'LendingTree' & BOOKED_MONTH = &BOOK_MONTH & ENTYRMONTH = &LEADYRMONTH;
RUN;

ODS EXCEL CLOSE;
ODS EXCEL OPTIONS(SHEET_INTERVAL="NONE");

TITLE "Credit Karma";

PROC TABULATE 
	DATA = ALL_LEADS_3 MISSING;
	CLASS SUPERVISOR VP LEADYRMONTH LEADSTATE;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADYRMONTH, 
		TOTALLEADS * F = comma18.0 
		PREAPPROVED_FLAG = "# Auto Apprv" * F = comma18.0 
		PREAPPROVED_FLAG = "% approve" * ROWPCTSUM < TOTALLEADS > * F = PCTPIC./NOCELLMERGE;
	WHERE SOURCE = 'CreditKarma' & LEADYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3 MISSING;
	CLASS SUPERVISOR VP LEADYRMONTH LEADSTATE;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADYRMONTH * SUPERVISOR ALL, 
		TOTALLEADS * F = comma18.0 
		PREAPPROVED_FLAG = "# Auto Apprv" * F = comma18.0 
		PREAPPROVED_FLAG = "% approve" * ROWPCTSUM < TOTALLEADS > * F = PCTPIC./NOCELLMERGE;
	BY VP;
	WHERE SOURCE = 'CreditKarma' & LEADYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3 MISSING;
	CLASS SUPERVISOR VP BOOKED_MONTH LEADSTATE;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES BOOKED_MONTH * SUPERVISOR ALL, 
		BOOKED = "BOOKED" * F = comma18.0 
		NETLOANAMOUNT = "$ BOOKED" * F = dollar18.0 
		NETLOANAMOUNT * MEAN = "avg adv" * F = dollar18.0/NOCELLMERGE;
	BY VP;
	WHERE SOURCE = 'CreditKarma' & BOOKED_MONTH = &BOOK_MONTH & ENTYRMONTH = &LEADYRMONTH;
RUN;

ODS EXCEL CLOSE;
ODS EXCEL OPTIONS(SHEET_INTERVAL="NONE");

TITLE "SuperMoney LLC";

PROC TABULATE 
	DATA = ALL_LEADS_3 MISSING;
	CLASS SUPERVISOR VP LEADYRMONTH LEADSTATE;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADYRMONTH, 
		TOTALLEADS * F = comma18.0 
		PREAPPROVED_FLAG = "# Auto Apprv" * F = comma18.0 
		PREAPPROVED_FLAG = "% approve" * ROWPCTSUM < TOTALLEADS > * F = PCTPIC./NOCELLMERGE;
	WHERE SOURCE = 'SuperMoney LLC' & LEADYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3 MISSING;
	CLASS SUPERVISOR VP LEADYRMONTH LEADSTATE;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADYRMONTH * SUPERVISOR ALL, 
		TOTALLEADS * F = comma18.0 
		PREAPPROVED_FLAG = "# Auto Apprv" * F = comma18.0 
		PREAPPROVED_FLAG = "% approve" * ROWPCTSUM < TOTALLEADS > * F = PCTPIC./NOCELLMERGE;
	BY VP;
	WHERE SOURCE = 'SuperMoney LLC' & LEADYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3 MISSING;
	CLASS SUPERVISOR VP BOOKED_MONTH LEADSTATE;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES BOOKED_MONTH * SUPERVISOR ALL, 
		BOOKED = "BOOKED" * F = comma18.0 
		NETLOANAMOUNT = "$ BOOKED" * F = dollar18.0 
		NETLOANAMOUNT * MEAN = "avg adv" * F = dollar18.0/NOCELLMERGE;
	BY VP;
	WHERE SOURCE = 'SuperMoney LLC' & BOOKED_MONTH = &BOOK_MONTH & ENTYRMONTH = &LEADYRMONTH;
RUN;

ODS EXCEL CLOSE;

*** BY AMTBUCKET ------------------------------------------------- ***;
%LET LEADMONTH = 03;
%LET LEADYRMONTH = 202003;
%LET BOOK_MONTH = 03;

ODS EXCEL;
TITLE "Web Leads";

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS LEADYRMONTH LEADSTATE AMTBUCKET;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES AMTBUCKET ALL, 
		TOTALLEADS * F = comma18.0 
		PREAPPROVED_FLAG = "# Auto Apprv" * F = comma18.0 
		PREAPPROVED_FLAG = "% approve" * ROWPCTSUM < TOTALLEADS > * F = PCTPIC./NOCELLMERGE;
	WHERE SOURCE = 'Web Leads' & LEADYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS BOOKED_MONTH LEADSTATE AMTBUCKET;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES AMTBUCKET ALL, 
		BOOKED = "BOOKED" * F = comma18.0 
		NETLOANAMOUNT = "$ BOOKED" * F = dollar18.0 
		NETLOANAMOUNT * MEAN = "avg adv" * F = dollar18.0 
		NETLOANAMOUNT * min = "Bk Min $" * F = dollar18.0 
		NETLOANAMOUNT * max = "Bk Max $" * F = dollar18.0/NOCELLMERGE;
	WHERE SOURCE = 'Web Leads' & BOOKED_MONTH = &BOOK_MONTH & ENTYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS LEADYRMONTH LEADSTATE AMTBUCKET;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADSTATE * AMTBUCKET ALL, 
		TOTALLEADS * F = comma18.0 
		PREAPPROVED_FLAG = "# Auto Apprv" * F = comma18.0 
		PREAPPROVED_FLAG = "% approve" * ROWPCTSUM < TOTALLEADS > * F = PCTPIC./NOCELLMERGE;
	WHERE SOURCE = 'Web Leads' & LEADYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS BOOKED_MONTH LEADSTATE AMTBUCKET;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADSTATE * AMTBUCKET ALL, 
		BOOKED = "BOOKED" * F = comma18.0 
		NETLOANAMOUNT = "$ BOOKED" * F = dollar18.0 
		NETLOANAMOUNT * MEAN = "avg adv" * F = dollar18.0 
		NETLOANAMOUNT * min = "Bk Min $" * F = dollar18.0 
		NETLOANAMOUNT * max = "Bk Max $" * F = dollar18.0/NOCELLMERGE;
	WHERE SOURCE = 'Web Leads' & BOOKED_MONTH = &BOOK_MONTH & ENTYRMONTH = &LEADYRMONTH;
RUN;

ODS EXCEL CLOSE;

*** BY AMTBUCKET ------------------------------------------------- ***;
%LET LEADMONTH = 03;
%LET LEADYRMONTH = 202003;
%LET BOOK_MONTH = 03;

ODS EXCEL;
TITLE "Lending Tree";

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS LEADYRMONTH LEADSTATE AMTBUCKET;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES AMTBUCKET ALL, 
		TOTALLEADS * F = comma18.0 
		PREAPPROVED_FLAG = "# Auto Apprv" * F = comma18.0 
		PREAPPROVED_FLAG = "% approve" * ROWPCTSUM < TOTALLEADS > * F = PCTPIC./NOCELLMERGE;
	WHERE SOURCE = 'LendingTree' & LEADYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS BOOKED_MONTH LEADSTATE AMTBUCKET;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES AMTBUCKET ALL, 
		BOOKED = "BOOKED" * F = comma18.0 
		NETLOANAMOUNT = "$ BOOKED" * F = dollar18.0 
		NETLOANAMOUNT * MEAN = "avg adv" * F = dollar18.0 
		NETLOANAMOUNT * min = "Bk Min $" * F = dollar18.0 
		NETLOANAMOUNT * max = "Bk Max $" * F = dollar18.0/NOCELLMERGE;
	WHERE SOURCE = 'LendingTree' & BOOKED_MONTH = &BOOK_MONTH & ENTYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS LEADYRMONTH LEADSTATE AMTBUCKET;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADSTATE * AMTBUCKET ALL, 
		TOTALLEADS * F = comma18.0 
		PREAPPROVED_FLAG = "# Auto Apprv" * F = comma18.0 
		PREAPPROVED_FLAG = "% approve" * ROWPCTSUM < TOTALLEADS > * F = PCTPIC./NOCELLMERGE;
	WHERE SOURCE = 'LendingTree' & LEADYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS BOOKED_MONTH LEADSTATE AMTBUCKET;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADSTATE * AMTBUCKET ALL, 
		BOOKED = "BOOKED" * F = comma18.0 
		NETLOANAMOUNT = "$ BOOKED" * F = dollar18.0 
		NETLOANAMOUNT * MEAN = "avg adv" * F = dollar18.0 
		NETLOANAMOUNT * min = "Bk Min $" * F = dollar18.0 
		NETLOANAMOUNT * max = "Bk Max $" * F = dollar18.0/NOCELLMERGE;
	WHERE SOURCE = 'LendingTree' & BOOKED_MONTH = &BOOK_MONTH & ENTYRMONTH = &LEADYRMONTH;
RUN;

ODS EXCEL CLOSE;

*** BY AMTBUCKET ------------------------------------------------- ***;
%LET LEADMONTH = 03;
%LET LEADYRMONTH = 202003;
%LET BOOK_MONTH = 03;

ODS EXCEL;
TITLE "Credit Karma";

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS LEADYRMONTH LEADSTATE AMTBUCKET;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES AMTBUCKET ALL, 
		TOTALLEADS * F = comma18.0 
		PREAPPROVED_FLAG = "# Auto Apprv" * F = comma18.0 
		PREAPPROVED_FLAG = "% approve" * ROWPCTSUM < TOTALLEADS > * F = PCTPIC./NOCELLMERGE;
	WHERE SOURCE = 'CreditKarma' & LEADYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS BOOKED_MONTH LEADSTATE AMTBUCKET;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES AMTBUCKET ALL, 
		BOOKED = "BOOKED" * F = comma18.0 
		NETLOANAMOUNT = "$ BOOKED" * F = dollar18.0 
		NETLOANAMOUNT * MEAN = "avg adv" * F = dollar18.0 
		NETLOANAMOUNT * min = "Bk Min $" * F = dollar18.0 
		NETLOANAMOUNT * max = "Bk Max $" * F = dollar18.0/NOCELLMERGE;
	WHERE SOURCE = 'CreditKarma' & BOOKED_MONTH = &BOOK_MONTH & ENTYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS LEADYRMONTH LEADSTATE AMTBUCKET;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADSTATE * AMTBUCKET ALL, 
		TOTALLEADS * F = comma18.0 
		PREAPPROVED_FLAG = "# Auto Apprv" * F = comma18.0 
		PREAPPROVED_FLAG = "% approve" * ROWPCTSUM < TOTALLEADS > * F = PCTPIC./NOCELLMERGE;
	WHERE SOURCE = 'CreditKarma' & LEADYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS BOOKED_MONTH LEADSTATE AMTBUCKET;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADSTATE * AMTBUCKET ALL, 
		BOOKED = "BOOKED" * F = comma18.0 
		NETLOANAMOUNT = "$ BOOKED" * F = dollar18.0 
		NETLOANAMOUNT * MEAN = "avg adv" * F = dollar18.0 
		NETLOANAMOUNT * min = "Bk Min $" * F = dollar18.0 
		NETLOANAMOUNT * max = "Bk Max $" * F = dollar18.0/NOCELLMERGE;
	WHERE SOURCE = 'CreditKarma' & BOOKED_MONTH = &BOOK_MONTH & ENTYRMONTH = &LEADYRMONTH;
RUN;

ODS EXCEL CLOSE;

*** BY AMTBUCKET ------------------------------------------------- ***;
%LET LEADMONTH = 03;
%LET LEADYRMONTH = 202003;
%LET BOOK_MONTH = 03;

ODS EXCEL;
TITLE "SuperMoney LLC";

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS LEADYRMONTH LEADSTATE AMTBUCKET;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES AMTBUCKET ALL, 
		TOTALLEADS * F = comma18.0 
		PREAPPROVED_FLAG = "# Auto Apprv" * F = comma18.0 
		PREAPPROVED_FLAG = "% approve" * ROWPCTSUM < TOTALLEADS > * F = PCTPIC./NOCELLMERGE;
	WHERE SOURCE = 'SuperMoney LLC' & LEADYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS BOOKED_MONTH LEADSTATE AMTBUCKET;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES AMTBUCKET ALL, 
		BOOKED = "BOOKED" * F = comma18.0 
		NETLOANAMOUNT = "$ BOOKED" * F = dollar18.0 
		NETLOANAMOUNT * MEAN = "avg adv" * F = dollar18.0 
		NETLOANAMOUNT * min = "Bk Min $" * F = dollar18.0 
		NETLOANAMOUNT * max = "Bk Max $" * F = dollar18.0/NOCELLMERGE;
	WHERE SOURCE = 'SuperMoney LLC' & BOOKED_MONTH = &BOOK_MONTH & ENTYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS LEADYRMONTH LEADSTATE AMTBUCKET;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADSTATE * AMTBUCKET ALL, 
		TOTALLEADS * F = comma18.0 
		PREAPPROVED_FLAG = "# Auto Apprv" * F = comma18.0 
		PREAPPROVED_FLAG = "% approve" * ROWPCTSUM < TOTALLEADS > * F = PCTPIC./NOCELLMERGE;
	WHERE SOURCE = 'SuperMoney LLC' & LEADYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS BOOKED_MONTH LEADSTATE AMTBUCKET;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADSTATE * AMTBUCKET ALL, 
		BOOKED = "BOOKED" * F = comma18.0 
		NETLOANAMOUNT = "$ BOOKED" * F = dollar18.0 
		NETLOANAMOUNT * MEAN = "avg adv" * F = dollar18.0 
		NETLOANAMOUNT * min = "Bk Min $" * F = dollar18.0 
		NETLOANAMOUNT * max = "Bk Max $" * F = dollar18.0/NOCELLMERGE;
	WHERE SOURCE = 'SuperMoney LLC' & BOOKED_MONTH = &BOOK_MONTH & ENTYRMONTH = &LEADYRMONTH;
RUN;

ODS EXCEL CLOSE;

*** LT FILTER ROUTING ID ----------------------------------------- ***;
TITLE;

PROC FORMAT;
	PICTURE PCTPIC (ROUND) LOW-HIGH='09.00%';
RUN; 

PROC SORT 
	DATA = ALL_LEADS_3;
	BY SOURCE;
RUN;

ODS EXCEL OPTIONS(SHEET_INTERVAL = "NONE");
TITLE "Lending Tree";

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS LEADYRMONTH LEADSTATE LTFILTER_ROUTINGID;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADSTATE * LTFILTER_ROUTINGID ALL, 
		TOTALLEADS * F = comma18.0 
		PREAPPROVED_FLAG = "# Auto Apprv" * F = comma18.0 
		PREAPPROVED_FLAG = "% approve" * ROWPCTSUM < TOTALLEADS > * F = PCTPIC./NOCELLMERGE;
	BY SOURCE;
	WHERE SOURCE = 'LendingTree' & LEADYRMONTH = &LEADYRMONTH;
RUN;

PROC TABULATE 
	DATA = ALL_LEADS_3;
	CLASS BOOKED_MONTH LEADSTATE LTFILTER_ROUTINGID;
	VAR TOTALLEADS PREAPPROVED_FLAG BOOKED NETLOANAMOUNT;
	TABLES LEADSTATE * LTFILTER_ROUTINGID ALL, 
		BOOKED = "BOOKED" * F = comma18.0 
		NETLOANAMOUNT = "$ BOOKED" * F = dollar18.0 
		NETLOANAMOUNT * MEAN = "avg adv" * F = dollar18.0/NOCELLMERGE;
	WHERE SOURCE = 'LendingTree' & BOOKED_MONTH = &BOOK_MONTH & ENTYRMONTH = &LEADYRMONTH;
RUN;
ODS EXCEL CLOSE;


